### PR TITLE
Add 2019 CRS files

### PR DESCRIPTION
**Pull request by amy-silcock**
Files provided by Duncan. As per: https://github.com/devinit/D-Portal/issues/601

### CODE REVIEW

**Review by notshi — APPROVED** [review]
Thanks, both for doing these so quickly.

**Comment by PetyaKangalova** [comment]
@notshi  when would the 2019 data be live on d-portal? As far as I can see it still refer to CRS 2018. Thanks!

**Comment by notshi** [comment]
Thanks, @PetyaKangalova the 2019 data is now live on the site but we will need an analyst to take a look and make sure the numbers are as expected.

We also need an analyst to update the mapping of CRS and IATI funders names as the last time this was updated was around 2017.

https://github.com/devinit/D-Portal/blob/master/dstore/csv/crs_funders.csv
https://github.com/devinit/D-Portal/blob/master/dstore/csv/iati_funders.csv

Information about them can be found [here](https://github.com/devinit/D-Portal/tree/master/dstore/csv#public-spreadsheet-csv).

**Comment by PetyaKangalova** [comment]
@notshi  thanks! I can see you have now updated the year on the front end as well- think that is where the confusion was coming  from in the  "Where does the money come from?" table. Can you let me know  the date when the 2019 data went live? Reason for asking is that for a report PWYF pulled data at the end of Jan and I wanted to confirm if it was still the 2018 CRS data.

On updating the mapping for CRS and IATI, I'll assign to one of our business analysts and get back to you in a week's time to let you know where we have gone to.

**Comment by notshi** [comment]
Many thanks, @PetyaKangalova the data went live just now.

We received the data on the 3rd of Feb so PWYF would still be getting 2018 CRS data if they pulled it end of Jan.

**Comment by amy-silcock** [comment]
Hi @notshi ,

Are there particular columns that you use in d-portal?
https://github.com/devinit/D-Portal/blob/master/dstore/csv/crs_funders.csv
https://github.com/devinit/D-Portal/blob/master/dstore/csv/iati_funders.csv

For example in iati-funders, I'm not sure where the Funder-code and abbreviations come from.
Maybe it's an old classification from the DAC or something we've created specifically for d-portal?

Mapping different UK Gov departments to the funder-code GB makes sense. And likewise for other countries.
Not sure which organisations get mapped to XM or INGO and why? Do we need to include these ones?

In crs_funders am I okay to create some new funder codes for new organisations that aren't yet on either list? Or can you point me to the source of these codes?

Happy to have a call if that's easier!

**Comment by notshi** [comment]
Hi @amy-silcock we have some documentation below - hope it helps!

For iati_funders, we don't use the abbreviations but have left them there for prosperity and context.
We only use columns 1 and two. [More info](https://github.com/devinit/D-Portal/blob/master/dstore/csv/README.md#iati_funderscsv-maps-iati-publishers-to-their-crs-identifiers)

As for XM or INGO, we aren't sure why they are mapped a certain way as these lists were given to us a long time ago by the tech team and analysts involved then.

Looking at the crs_funders, XM is matched to [Organisation for Security and Co-operation in Europe](https://github.com/devinit/D-Portal/blob/master/dstore/csv/crs_funders.csv#L54) so all organisations in the iati_funders that are labelled as XM will be collated under this umbrella.

And yes, you can create new funders for new organisations. [More info](https://github.com/devinit/D-Portal/blob/master/dstore/csv/README.md#crs_funderscsv-maps-crs-publishers-to-their-iati-identifiers)

**Pull request merged**
